First try

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,28 @@
 #!/usr/bin/env bash
-# To take 4 parameters to transfer a file from our client to a server
-if [ $# -lt 3 ]; then
-    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
+# Function to display usage
+display_usage() {
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+}
+
+# Check if the number of arguments is less than 4
+if [ $# -lt 4 ]; then
+    display_usage
     exit 1
 fi
-scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/$1"
+
+# Assign arguments to variables
+PATH_TO_FILE=$1
+IP=$2
+USERNAME=$3
+PATH_TO_SSH_KEY=$4
+
+# Transfer the file using scp with strict host key checking disabled
+scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+# Check if the scp command was successful
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
+else
+    echo "File transfer failed."
+    exit 1
+fi
